services:
  db_test:
    build: ./dataBase
    container_name: dataBase_RetoFactus_test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin.123
      POSTGRES_DB: retoFactus
    ports:
      - "5432:5432"
    volumes:
      - postgres_DP_test:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d retoFactus"]
      interval: 10s
      timeout: 15s
      retries: 5

volumes:
  postgres_DP_test:
